In [0]:
import pandas as pd

In [0]:
df = pd.read_csv("retail_sales_dataset.csv")
df.head()

   Transaction ID        Date  ... Price per Unit Total Amount
0               1  2023-11-24  ...             50          150
1               2  2023-02-27  ...            500         1000
2               3  2023-01-13  ...             30           30
3               4  2023-05-21  ...            500          500
4               5  2023-05-06  ...             50          100

[5 rows x 9 columns]

In [0]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [0]:
df["Product Category"].unique()

array(['Beauty', 'Clothing', 'Electronics'], dtype=object)

In [0]:
df.groupby("Product Category")["Total Amount"].agg(["sum","mean","max","min","count"])

                     sum        mean   max  min  count
Product Category
Beauty            143515  467.475570  2000   25    307
Clothing          155580  443.247863  2000   25    351
Electronics       156905  458.786550  2000   25    342

In [0]:
df.groupby("Product Category")["Price per Unit"].max()

Product Category
Beauty         500
Clothing       500
Electronics    500
Name: Price per Unit, dtype: int64

In [0]:
df.groupby("Price per Unit")["Total Amount"].sum().sort_values(ascending = True)

Price per Unit
25      13050
30      13350
50      26700
300    155400
500    247500
Name: Total Amount, dtype: int64

In [0]:
#Sorting of data by a specific column

df.sort_values(by="Gender", ascending = False).head(5)

     Transaction ID        Date  ... Price per Unit Total Amount
0                 1  2023-11-24  ...             50          150
596             597  2023-08-22  ...            300         1200
550             551  2023-07-14  ...            300          900
552             553  2023-03-31  ...            300         1200
554             555  2023-10-19  ...            300          300

[5 rows x 9 columns]

### Feature Engineering

In [0]:
df.head()

   Transaction ID        Date  ... Total Amount Discount
0               1  2023-11-24  ...          150     30.0
1               2  2023-02-27  ...         1000    200.0
2               3  2023-01-13  ...           30      6.0
3               4  2023-05-21  ...          500    100.0
4               5  2023-05-06  ...          100     20.0

[5 rows x 10 columns]

In [0]:
df["Discount"] = df["Total Amount"]* 0.20
df.head()

   Transaction ID        Date  ... Total Amount Discount
0               1  2023-11-24  ...        120.0     24.0
1               2  2023-02-27  ...        800.0    160.0
2               3  2023-01-13  ...         24.0      4.8
3               4  2023-05-21  ...        400.0     80.0
4               5  2023-05-06  ...         80.0     16.0

[5 rows x 10 columns]

In [0]:
df["Final Amount"] = df["Total Amount"] - df["Discount"]
df.head()

   Transaction ID        Date Customer ID  ... Total Amount  Discount Final Amount
0               1  2023-11-24     CUST001  ...        120.0      24.0         96.0
1               2  2023-02-27     CUST002  ...        800.0     160.0        640.0
2               3  2023-01-13     CUST003  ...         24.0       4.8         19.2
3               4  2023-05-21     CUST004  ...        400.0      80.0        320.0
4               5  2023-05-06     CUST005  ...         80.0      16.0         64.0

[5 rows x 11 columns]