In [0]:
#Creating a data using dictionary

dict_data = {"Name": ["Lerato", "Peggy", "Ane", "Rogator"],
             "Age" : [32, 28, 15, 33],
             "City": ["Joburg", "Cape Town", "Durban","PE"]
             }

Now change the above data into dataframe using pandas

In [0]:
import pandas as pd  #required to convert dict into dataframe

df = pd.DataFrame(dict_data)
print(df)

      Name  Age       City
0   Lerato   32     Joburg
1    Peggy   28  Cape Town
2      Ane   15     Durban
3  Rogator   33         PE

In [0]:
#To show top rows only - in this case only top 3

df.head(3)

     Name  Age       City
0  Lerato   32     Joburg
1   Peggy   28  Cape Town
2     Ane   15     Durban

In [0]:
df.shape  #this is to get a complete number of rows and coloumns

(4, 3)

In [0]:
df.info() #this is to get datatype for each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

### EDA - Exploratory Data Analysis

### Lets now upload data to show bigger data for EDA purposes:

In [0]:
df = pd.read_csv("retail_sales_dataset.csv")
df.head()

   Transaction ID        Date  ... Price per Unit Total Amount
0               1  2023-11-24  ...             50          150
1               2  2023-02-27  ...            500         1000
2               3  2023-01-13  ...             30           30
3               4  2023-05-21  ...            500          500
4               5  2023-05-06  ...             50          100

[5 rows x 9 columns]

In [0]:
df.shape

(1000, 9)

EDA - Now doing exploratory data analysis

In [0]:
#This is to show the info in the columns, data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

### FOR STATS DISPLAY OR BASIC CALCULATION:

### mean, min, max, ave, count, etc.

In [0]:
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

Run a code to show all columns:

In [0]:
df.columns

Index(['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount'],
      dtype='object')

Now show add up the total amount of the column above and print:

In [0]:
df["Total Amount"].sum()

np.int64(456000)

In [0]:
print(df["Total Amount"].sum())

456000

In [0]:
# Calculate the ave of the Total Amount column
print(df["Total Amount"].mean())

456.0

In [0]:
# How to access specific columns, instead of the entire dataframe

df["Product Category"]

0           Beauty
1         Clothing
2      Electronics
3         Clothing
4           Beauty
          ...
995       Clothing
996         Beauty
997         Beauty
998    Electronics
999    Electronics
Name: Product Category, Length: 1000, dtype: object

In [0]:
df[["Product Category", "Gender"]]

    Product Category  Gender
0             Beauty    Male
1           Clothing  Female
2        Electronics    Male
3           Clothing    Male
4             Beauty    Male
..               ...     ...
995         Clothing    Male
996           Beauty    Male
997           Beauty  Female
998      Electronics  Female
999      Electronics    Male

[1000 rows x 2 columns]

In [0]:
df[["Product Category", "Age", "Gender"]].head()

  Product Category  Age  Gender
0           Beauty   34    Male
1         Clothing   26  Female
2      Electronics   50    Male
3         Clothing   37    Male
4           Beauty   30    Male

In [0]:
#Another way would be to access the column then place an object in front as a variable.

new_columns = df[["Age","Gender","Customer ID"]]
print(new_columns.head())

   Age  Gender Customer ID
0   34    Male     CUST001
1   26  Female     CUST002
2   50    Male     CUST003
3   37    Male     CUST004
4   30    Male     CUST005

In [0]:
#We can also access the rows only using the iloc() fucntion.

df.iloc[0]  #to access the first row and values

Transaction ID               1
Date                2023-11-24
Customer ID            CUST001
Gender                    Male
Age                         34
Product Category        Beauty
Quantity                     3
Price per Unit              50
Total Amount               150
Name: 0, dtype: object

In [0]:
#Access the last row

df.iloc[-1].head()

Transaction ID          1000
Date              2023-04-12
Customer ID         CUST1000
Gender                  Male
Age                       47
Name: 999, dtype: object

In [0]:
# How to access multiple rows, the beauty of using dataframes is we don't need to loop like lists!

df.iloc[0:4].head() #gives the first four rows

   Transaction ID        Date  ... Price per Unit Total Amount
0               1  2023-11-24  ...             50          150
1               2  2023-02-27  ...            500         1000
2               3  2023-01-13  ...             30           30
3               4  2023-05-21  ...            500          500

[4 rows x 9 columns]

In [0]:
# Access column less than age 20

df["Age"].head() < 20  #returns a boolean because it's a condition.

0    False
1    False
2    False
3    False
4    False
Name: Age, dtype: bool

In [0]:
df[df["Age"] < 20]

     Transaction ID        Date  ... Price per Unit Total Amount
15               16  2023-02-17  ...            500         1500
21               22  2023-10-15  ...             50          100
36               37  2023-05-23  ...             25           75
57               58  2023-11-13  ...            300         1200
61               62  2023-12-27  ...             50          100
73               74  2023-11-22  ...            500         2000
85               86  2023-11-08  ...             30           90
116             117  2023-03-15  ...            500         1000
147             148  2023-05-09  ...             30           60
168             169  2023-11-17  ...            500         1500
180             181  2023-11-03  ...            300         1200
256             257  2023-02-19  ...            500         2000
265             266  2023-12-01  ...             30           60
282             283  2023-05-08  ...            500          500
299             300  2023-01-31  ...             50          200
302             303  2023-01-02  ...             30           90
304             305  2023-05-16  ...             30           30
325             326  2023-09-15  ...             25           75
363             364  2023-08-23  ...            500          500
390             391  2023-01-05  ...             25           50
411             412  2023-09-16  ...            500         2000
460             461  2023-03-25  ...            500         1000
468             469  2023-05-08  ...             25           75
483             484  2023-01-13  ...            300         1200
513             514  2023-03-01  ...            300          300
529             530  2023-02-05  ...             30          120
532             533  2023-11-16  ...            500         1500
537             538  2023-09-17  ...             50          150
555             556  2023-06-04  ...             50           50
593             594  2023-09-01  ...            300          600
594             595  2023-11-09  ...            500         2000
600             601  2023-04-10  ...             30           30
627             628  2023-11-01  ...             50          200
676             677  2023-10-27  ...            500         1500
678             679  2023-01-11  ...             30           90
708             709  2023-07-21  ...            500         1000
713             714  2023-02-12  ...            500          500
811             812  2023-11-12  ...             25           75
836             837  2023-07-01  ...             30           90
846             847  2023-04-08  ...            300         1200
978             979  2023-01-02  ...             25           25
984             985  2023-05-30  ...             25           50

[42 rows x 9 columns]

### Now calling rows by age, in this case condition is age is less than 20

In [0]:
#Run the same code and reduce rows to 5 only

df[df["Age"] <20].head()

    Transaction ID        Date  ... Price per Unit Total Amount
15              16  2023-02-17  ...            500         1500
21              22  2023-10-15  ...             50          100
36              37  2023-05-23  ...             25           75
57              58  2023-11-13  ...            300         1200
61              62  2023-12-27  ...             50          100

[5 rows x 9 columns]

### NB!!! iloc accessess rows and loc accesses columns using index position

In [0]:
#Group or count how many transactions are in each product category using value_counts()function

df["Product Category"].value_counts()

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [0]:
# Now group each a specific column by another one using groupby() function

df.groupby("Product Category")["Age"].max()

Product Category
Beauty         64
Clothing       64
Electronics    64
Name: Age, dtype: int64

In [0]:
df.groupby("Product Category")["Age"].mean()

Product Category
Beauty         40.371336
Clothing       41.948718
Electronics    41.736842
Name: Age, dtype: float64

###