Mini Exercise
Challenge??

Using pandas, answer:

which product category has:


- highest revenue
- lowest revenue


Which Gender spends more on average


show top 5 transactions


Assuming the Total amount excludes VAT, create:


VAT column

Final Amount column

Average Transaction value

Most common product category

In [0]:
import pandas as pd

In [0]:
df = pd.read_csv('retail_sales_dataset.csv')
df.head()

   Transaction ID        Date  ... Price per Unit Total Amount
0               1  2023-11-24  ...             50          150
1               2  2023-02-27  ...            500         1000
2               3  2023-01-13  ...             30           30
3               4  2023-05-21  ...            500          500
4               5  2023-05-06  ...             50          100

[5 rows x 9 columns]

### Product category with highest revenue:

In [0]:
df.sort_values("Total Amount", ascending = False).head()

     Transaction ID        Date  ... Price per Unit Total Amount
571             572  2023-04-20  ...            500         2000
88               89  2023-10-01  ...            500         2000
502             503  2023-10-25  ...            500         2000
560             561  2023-05-27  ...            500         2000
831             832  2023-09-11  ...            500         2000

[5 rows x 9 columns]

### Product category with lowest revenue:

In [0]:
df.sort_values("Total Amount", ascending = True).head()

     Transaction ID        Date  ... Price per Unit Total Amount
422             423  2023-03-08  ...             25           25
241             242  2023-05-02  ...             25           25
235             236  2023-04-28  ...             25           25
231             232  2023-02-06  ...             25           25
906             907  2023-01-08  ...             25           25

[5 rows x 9 columns]

The answer is clothing for both highest revenue and lowest revenue

### Which gender spends more on average?

In [0]:
df.groupby("Gender")["Total Amount"].mean()

Gender
Female    456.549020
Male      455.428571
Name: Total Amount, dtype: float64

The answer is Females spend more on average

### Show top 5 transactions

In [0]:
df.sort_values("Total Amount", ascending = False).head()

     Transaction ID        Date  ... Price per Unit Total Amount
571             572  2023-04-20  ...            500         2000
88               89  2023-10-01  ...            500         2000
502             503  2023-10-25  ...            500         2000
560             561  2023-05-27  ...            500         2000
831             832  2023-09-11  ...            500         2000

[5 rows x 9 columns]

### Assuming the Total amount excludes VAT, create:

### VAT column 

### Final Amount column 

### Average Transaction value 

### Most common product category

In [0]:
# VAT Column

df["VAT"] = df["Total Amount"] * 0.15
df.head(3)

   Transaction ID        Date Customer ID  ... Price per Unit  Total Amount    VAT
0               1  2023-11-24     CUST001  ...             50           150   22.5
1               2  2023-02-27     CUST002  ...            500          1000  150.0
2               3  2023-01-13     CUST003  ...             30            30    4.5

[3 rows x 10 columns]

In [0]:
#Final amount column

df["Final Amount"] = df["Total Amount"] + df["VAT"]
df.head(3)

   Transaction ID        Date Customer ID  ... Total Amount    VAT Final Amount
0               1  2023-11-24     CUST001  ...          150   22.5        172.5
1               2  2023-02-27     CUST002  ...         1000  150.0       1150.0
2               3  2023-01-13     CUST003  ...           30    4.5         34.5

[3 rows x 11 columns]

In [0]:
#Average Tansaction value

print(df["Final Amount"].mean())

524.4

In [0]:
#Most common product category

df["Product Category"].mode()

0    Clothing
Name: Product Category, dtype: object